export const AppLocalizationKeys = {
    common: {
        action_close: 'common.action_close',
        action_retry: 'common.action_retry',
        action_refresh: 'common.action_refresh',
        action_cancel: 'common.action_cancel',
        general_error: 'common.general_error',
        notification: 'common.notification',
        theme_mode: 'common.theme_mode',
        theme_mode_light: 'common.theme_mode_light',
        theme_mode_dark: 'common.theme_mode_dark',
        select_language: 'common.select_language',
        language: {
            en: 'common.language.en',
            vi: 'common.language.vi',
        },
    },
    connection_banner: {
        connected: 'connection_banner.connected',
        connecting: 'connection_banner.connecting',
        not_connected: 'connection_banner.not_connected',
        not_reachable: 'connection_banner.not_reachable',
    },
    login: {
        page_title: 'login.page_title',
        email_or_phone_title: 'login.email_or_phone_title',
        email_or_phone_placeholder: 'login.email_or_phone_placeholder',
        email_or_phone_empty_error_message: 'login.email_or_phone_empty_error_message',
        email_wrong_format_error_message: 'login.email_wrong_format_error_message',
        phone_wrong_format_error_message: 'login.phone_wrong_format_error_message',
        password_title: 'login.password_title',
        password_placeholder: 'login.password_placeholder',
        password_empty_error_message: 'login.password_empty_error_message',
        password_wrong_format_error_message: 'login.password_wrong_format_error_message',
        button_title: 'login.button_title',
        button_forgot_password: 'login.button_forgot_password',
        button_do_not_have_account: 'login.button_do_not_have_account',
        button_sign_up: 'login.button_sign_up',
    },
    register: {
        page_title: 'register.page_title',
        confirm_password: 'register.confirm_password',
        confirm_password_placeholder: 'register.confirm_password_placeholder',
        or_continue_with: 'register.or_continue_with',
        title_term_of_service: 'register.title_term_of_service',
        title_privacy_policy: 'register.title_privacy_policy',
        wrong_confirm_password: 'register.wrong_confirm_password',
    },
    otp: {
        title_page: 'otp.title_page',
        enter_the_verification_code: 'otp.enter_the_verification_code',
        did_not_receive_label: 'otp.did_not_receive_label',
        resend_label: 'otp.resend_label',
    },
    forgot_password: {
        page_title: 'forgot_password.page_title',
        confirm_mail_label: 'forgot_password.confirm_mail_label',
        write_your_email: 'forgot_password.write_your_email',
        email: 'forgot_password.email',
        email_placeholder: 'forgot_password.email_placeholder',
        email_empty_error: 'forgot_password.email_empty_error',
    },
    register_information: {
        step_label: 'register_information.step_label',
        step_completed_label: 'register_information.step_completed_label',
        step_in_progress_label: 'register_information.step_in_progress_label',
        step_pending_label: 'register_information.step_pending_label',
        step_information_label: 'register_information.step_information_label',
        step_occupation_label: 'register_information.step_occupation_label',
        step_current_level_label: 'register_information.step_current_level_label',
        step_confirmation_label: 'register_information.step_confirmation_label',
    },
    reset_password: {
        page_title: 'reset_password.page_title',
        enter_new_password_label: 'reset_password.enter_new_password_label',
        confirm_password_label: 'reset_password.confirm_password_label',
        enter_confirm_password_label: 'reset_password.enter_confirm_password_label',
        please_write_new_password_label: 'reset_password.please_write_new_password_label',
        confirm_password_button_label: 'reset_password.confirm_password_button_label',
    },
};
