export enum IconNameEnum {
    ArrowLeft = 'ArrowLeft',
    ArrowRight = 'ArrowRight',
    ArrowUp = 'ArrowUp',
    ArrowDown = 'ArrowDown',
    DoneIcon = 'DoneIcon',
    CrossSquareIcon = 'CrossSquareIcon',
    VerifiedEmailIcon = 'VerifiedEmailIcon',
    PasswordHideIcon = 'PasswordHideIcon',
    WifiOffIcon = 'WifiOffIcon',
    WifiOnlineIcon = 'WifiOnlineIcon',
    GoogleIcon = 'GoogleIcon',
    FacebookIcon = 'FacebookIcon',
    AgreeCheck = 'AgreeCheck',
    DegreeCheck = 'DegreeCheck',
    EyeClose = 'EyeClose',
    EyeOpen = 'EyeOpen',
    Erase = 'Erase',
    Information = 'Information',
    Occupation = 'Occupation',
    Level = 'Level',
    Confirmation = 'Confirmation',
}
