import {
    DELAY_NETWORK_RESPONSES,
    NETWORK_REQUESTS_LATENCY,
    LOG_REDUX,
    LOG_REQUESTS,
    SEND_DIRECT_MESSAGE,
    ENABLE_REDUX_LOGGER,
    ENABLE_REDUX_FLIPPER,
} from './local_env';

export default {
    DELAY_NETWORK_RESPONSES,
    NETWORK_REQUESTS_LATENCY,
    LOG_REDUX,
    LOG_REQUESTS,
    SEND_DIRECT_MESSAGE,
    ENABLE_REDUX_LOGGER,
    ENABLE_REDUX_FLIPPER,
};
